### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by danieljonasson123** [j0bro/com.ubnt.unifivideo#11]
Hi!
I´m on latest build. I always (since a couple of months and several builds) loose the ability to change recording mode or taking snapshots on my cameras. It works for some days and then stops. I have to reinstall the app and remake my flows. I´m taking snapshots of widh 800. Could that be an issue?
Is there any log I can grab?

2018-03-30 11:01:30.204 | Flow | Test | {"test_id":"e2693405-7818-4e32-bebc-956870aa2c48","card_uri":"homey:device:2434b6dc-53dd-4992-8020-2ad92c68c742","card_id":"ufv_set_recording_mode","card_type":"action","card_group":"then","card_index":0,"state":"passed"}
-- | -- | -- | --
2018-03-30 11:01:30.200 | Flow | Test | {"test_id":"e2693405-7818-4e32-bebc-956870aa2c48","card_uri":"homey:device:2434b6dc-53dd-4992-8020-2ad92c68c742","card_id":"ufv_set_recording_mode","card_type":"action","card_group":"then","card_index":0,"state":"running"}

No reaction on my cameras.
Reinstalling the app works, until next time. Wondering what could trigger it to not function?

**Comment by j0bro** [comment]
Hi @danieljonasson123, what is 'latest build' for you? And no, snapshots width can go up to maximum resolution of the camera, so 1920 is also possible.

**Comment by danieljonasson123** [comment]
I´m now on 1,5,11,
Yesterday it stopped working again. Took around a week until it stops
working. I will reinstall the app again and see how long it will last this
time.

2018-05-09 17:08 GMT+02:00 Jeroen Brosens <notifications@github.com>:

**Comment by j0bro** [comment]
Is this still valid? If not, I will close it.

**Comment by danieljonasson123** [comment]
Please close. I have moved on to unifi protect.

Best regards Daniel

Den tis 9 juli 2019 14:00Jeroen Brosens <notifications@github.com> skrev:

**Comment by j0bro** [comment]
Thanks. How is Protect working for you BTW? Any significant changes/benefits that warrant the upgrade?

**Comment by danieljonasson123** [comment]
I´m pretty happy with protect. Kinda neat and tidy running controller and
protect on the same unit. I ran the controller and unifi video on Ubuntu
virtual hosts earlier. Protect still lacks some major features like
possibility to have cron jobs copying recorded videos to cloud content etc.
Seems like geofencing is a coming feature though. If you aint looking for
getting a new UNIFi controller I might would wait and see what features are
being developed future on.

Den tis 9 juli 2019 kl 14:08 skrev Jeroen Brosens <notifications@github.com
