### ISSUE TITLE
Unifi G3 Flex

### ISSUE THREAD

**Issue by Lesterbonn** [j0bro/com.ubnt.unifivideo#12]
My G3 flex cannot be found, should it work?

**Comment by j0bro** [comment]
It is probably not supported if it uses a different device name than the regular G3; so unfortunately not supported at the moment.

**Comment by Lesterbonn** [comment]
The device name is UVC G3 Flex

**Comment by ferdw** [comment]
Any progress on adding this camera?

**Comment by Terra2000** [comment]
ny progress on adding this camera UVC G3 Flex ?

**Comment by sebbebebbe** [comment]
I would also like this camera to be added.

**Comment by j0bro** [comment]
Support was added in the recently published v0.9.3. Please verify if this can be closed.

**Comment by sebbebebbe** [comment]
Awesome thanks for the work put into this. Added nicely, however i cannot test them in any flow yet. None of my devices are showing when adding card to flow. This has probably something to do with the new rc version I am running.

**Comment by j0bro** [comment]
I also run this experimental version and my normal G3's and dome are working just fine. Can you at least see the snapshot in the app when you open the device?

**Comment by sebbebebbe** [comment]
Yes I can see the snapshots on all my G3-flex cameras.

**Comment by j0bro** [comment]
Good, so the camera model works, meaning this issue is fixed :)
