### ISSUE TITLE
Unifi G3 micro

### ISSUE THREAD

**Issue by eilko** [j0bro/com.ubnt.unifivideo#13]
support for the Unifi G3 micro would be great.

**Comment by j0bro** [comment]
Would you perhaps know which device name the micro has? I am guessing it is "UVC Micro" but I don't have one to test with.

**Comment by eilko** [comment]
I would say  UVC‑G3‑MICRO but is there a way I can check this?

**Comment by uffsingen** [comment]
Hostname of the camera is for me
UVC-G3-MIcro-8aad       
8aad is the last digits in the mac address
Name of the camera in NVR
UVC G3 Micro

Regards
Ulf

**Comment by j0bro** [comment]
Support was added in v0.9.3. Please verify if this can be closed.

**Comment by Krisstenswe** [comment]
I'm now running on 0.9.3 and my G3-Micro, G3-Pro and G3-Dome is up and running! Thnx!
