### ISSUE TITLE
Cannot connect to NVR

### ISSUE THREAD

**Issue by sejfr6** [j0bro/com.ubnt.unifivideo#15]
Hi,

Im not sure if this is related to new camera firmware or updates of homey firmware.
"There were no new devices found when im trying to scan for cameras. 

Work before but not after i reinstalled my NRV. 

Do you need to specify any port in the NRV feeld ? 
Support for FLEX should also be nice. 

If you needed any support for testing, please let me know. Im glad to help you out!

Thanks in advance!

**Comment by hockeymask** [comment]
have the same problem, if i fill in my ip to the NVR it dissapears next time i check settings and i cant add devices.

**Comment by Sjalabert** [comment]
I have also the same issue. Is the support/development stopped?

**Comment by steffjenl** [comment]
What do you see when you go to https://developer.athom.com/tools/app-settings? I had the same problem and with debugging it works again. I will look at it later when i have the issue again.

Only when i see no ip address you can discover new devices.

**Comment by Sjalabert** [comment]
He will not save the ip adres. After filling in api and click on ‘toepassen’ it will not save the IP adres.

Van: steffjenl <notifications@github.com>
Verzonden: zondag 23 juni 2019 14:49
Aan: j0bro/com.ubnt.unifivideo <com.ubnt.unifivideo@noreply.github.com>
CC: Sjalabert <Ivo.Jansen@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [j0bro/com.ubnt.unifivideo] Cannot connect to NVR (#15)


What do you see when you go to https://developer.athom.com/tools/app-settings<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.athom.com%2Ftools%2Fapp-settings&data=02%7C01%7C%7C7fbf3fcea3ca46c1347808d6f7d9335d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636968909568032832&sdata=b1e%2BmoTpcuSJEBvsFbAWzpJXJzVDx6yO526ybw6JKSQ%3D&reserved=0>? I had the same problem and with debugging it works again. I will look at it later when i have the issue again.

Only when i see no ip address you can discover new devices.

**Comment by steffjenl** [comment]
@Sjalabert what for camera do you have? I see that you are in The Netherlands? Do you know how to sideload an Homey App?

**Comment by Sjalabert** [comment]
Steffjenl, Ik heb de unifi 3G dome. Wat bedoel je met sideloaden?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: steffjenl <notifications@github.com>
Verzonden: Sunday, June 23, 2019 6:19:28 PM
Aan: j0bro/com.ubnt.unifivideo
CC: Sjalabert; Mention
Onderwerp: Re: [j0bro/com.ubnt.unifivideo] Cannot connect to NVR (#15)


@Sjalabert<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSjalabert&data=02%7C01%7C%7C89e868b386d84249c8c908d6f7f6917d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636969035699952859&sdata=pteVXE5PdFeSATcTuiSsmeXJnVBuz9QaZwi%2B02bLe6E%3D&reserved=0> what for camera do you have? I see that you are in The Netherlands? Do you know how to sideload an Homey App?

**Comment by steffjenl** [comment]
Je kan apps vanaf je computer/laptop op je homey installeren.

Meer informatie kan je vinden op https://developer.athom.com/

Mocht je daar niet uitkomen kan ik je eventueel helpen als je dat wilt.

Je moet wel wat ontwikkelaars applicaties installeren op je computer/laptop.

Ik denk dat ik het al heb gevonden, maar ervaar het probleem zelf niet meer en wil het graag testen.

**Comment by Sjalabert** [comment]
Oooh je bedoeld middels cli. Ik kan het proberen. Staat de repo op github?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: steffjenl <notifications@github.com>
Verzonden: Monday, June 24, 2019 1:03:17 AM
Aan: j0bro/com.ubnt.unifivideo
CC: Sjalabert; Mention
Onderwerp: Re: [j0bro/com.ubnt.unifivideo] Cannot connect to NVR (#15)

Je kan apps vanaf je computer/laptop op je homey installeren.

Meer informatie kan je vinden op https://developer.athom.com/

Mocht je daar niet uitkomen kan ik je eventueel helpen als je dat wilt.

Je moet wel wat ontwikkelaars applicaties installeren op je computer/laptop.

Ik denk dat ik het al heb gevonden, maar ervaar het probleem zelf niet meer en wil het graag testen.

Verstuurd vanaf mijn iPhone

Op 23 jun. 2019 om 23:16 heeft Sjalabert <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Steffjenl, Ik heb de unifi 3G dome. Wat bedoel je met sideloaden?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: steffjenl <notifications@github.com<mailto:notifications@github.com>>
Verzonden: Sunday, June 23, 2019 6:19:28 PM
Aan: j0bro/com.ubnt.unifivideo
CC: Sjalabert; Mention
Onderwerp: Re: [j0bro/com.ubnt.unifivideo] Cannot connect to NVR (#15)


@Sjalabert<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSjalabert&data=02%7C01%7C%7C89e868b386d84249c8c908d6f7f6917d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636969035699952859&sdata=pteVXE5PdFeSATcTuiSsmeXJnVBuz9QaZwi%2B02bLe6E%3D&reserved=0> what for camera do you have? I see that you are in The Netherlands? Do you know how to sideload an Homey App?

**Comment by steffjenl** [comment]
https://github.com/steffjenl/com.ubnt.unifivideo

De develop branch is de juiste..

**Comment by Sjalabert** [comment]
Goedemorgen 'steff',

Ik heb net middels CLI (remote he 😉 want we moeten tenslotte werken *whaha) de nieuwe app geinstalleerd. Heb netjes het IP adres van de NVR geinstalleerd met desbetrefende API. Hij wordt onthouden, dit is al een vooruit gang 🙂 Alleen kan ik mijn 'UVC G3 Dome' niet toevoegen.

Na het klikken/toevoegen van UVC-G3 krijg ik de melding 'er zijn geen nieuwe apparaten gevonden'.

Ook meerdere keren de app herstart, dit mag helaas niet baten. Is er nog iets wat ik over het hoofd zie 🙂

Alvast bedankt voor de super hulp.

#Homey4Life 😉

groeten uit het zuiden van Nederland waar het inmiddels 27 graden is.


________________________________
Van: steffjenl <notifications@github.com>
Verzonden: maandag 24 juni 2019 07:05
Aan: j0bro/com.ubnt.unifivideo
CC: Sjalabert; Mention
Onderwerp: Re: [j0bro/com.ubnt.unifivideo] Cannot connect to NVR (#15)

https://github.com/steffjenl/com.ubnt.unifivideo

De develop branch is de juiste..

Verstuurd vanaf mijn iPhone

Op 24 jun. 2019 om 06:22 heeft Sjalabert <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Oooh je bedoeld middels cli. Ik kan het proberen. Staat de repo op github?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: steffjenl <notifications@github.com<mailto:notifications@github.com>>
Verzonden: Monday, June 24, 2019 1:03:17 AM
Aan: j0bro/com.ubnt.unifivideo
CC: Sjalabert; Mention
Onderwerp: Re: [j0bro/com.ubnt.unifivideo] Cannot connect to NVR (#15)

Je kan apps vanaf je computer/laptop op je homey installeren.

Meer informatie kan je vinden op https://developer.athom.com/

Mocht je daar niet uitkomen kan ik je eventueel helpen als je dat wilt.

Je moet wel wat ontwikkelaars applicaties installeren op je computer/laptop.

Ik denk dat ik het al heb gevonden, maar ervaar het probleem zelf niet meer en wil het graag testen.

Verstuurd vanaf mijn iPhone

Op 23 jun. 2019 om 23:16 heeft Sjalabert <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> het volgende geschreven:

Steffjenl, Ik heb de unifi 3G dome. Wat bedoel je met sideloaden?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: steffjenl <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>>
Verzonden: Sunday, June 23, 2019 6:19:28 PM
Aan: j0bro/com.ubnt.unifivideo
CC: Sjalabert; Mention
Onderwerp: Re: [j0bro/com.ubnt.unifivideo] Cannot connect to NVR (#15)


@Sjalabert<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSjalabert&data=02%7C01%7C%7C89e868b386d84249c8c908d6f7f6917d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636969035699952859&sdata=pteVXE5PdFeSATcTuiSsmeXJnVBuz9QaZwi%2B02bLe6E%3D&reserved=0> what for camera do you have? I see that you are in The Netherlands? Do you know how to sideload an Homey App?

**Comment by j0bro** [comment]
Hey guys, great to see some activity here! I will soon perform some long overdue updates (support for the new Homey 2.0 Camera API) but all your comments and pull requests are more than welcome. Keep it coming!

**Comment by Sjalabert** [comment]
Sorry for the dutch 😉

________________________________
Van: Jeroen Brosens <notifications@github.com>
Verzonden: maandag 24 juni 2019 09:22
Aan: j0bro/com.ubnt.unifivideo
CC: Sjalabert; Mention
Onderwerp: Re: [j0bro/com.ubnt.unifivideo] Cannot connect to NVR (#15)


Hey guys, great to see some activity here! I will soon perform some long overdue updates (support for the new Homey 2.0 Camera API) but all your comments and pull requests are more than welcome. Keep it coming!

**Comment by steffjenl** [comment]
@j0bro Thank you! When SDK 2.2 is out with better support for cameras I will try to help.

**Comment by steffjenl** [comment]
@Sjalabert do you have tonight some time to debug the app? i think the name is different than the name i have. Do you have Slack or other chat application?

**Comment by Sjalabert** [comment]
Yes,

I can plan tonight some time, nog problem. I thought I have slack. Will contact you when I'm at home from work, OK?



________________________________
Van: steffjenl <notifications@github.com>
Verzonden: maandag 24 juni 2019 09:32
Aan: j0bro/com.ubnt.unifivideo
CC: Sjalabert; Mention
Onderwerp: Re: [j0bro/com.ubnt.unifivideo] Cannot connect to NVR (#15)


@Sjalabert<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSjalabert&data=02%7C01%7C%7C684e7afcd1a34c6cc84b08d6f8761d98%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636969583514420598&sdata=zUBh5eax3jrycqtCCp5Dp4Mr%2BiVQHkIKu626w6AXaak%3D&reserved=0> do you have tonight some time to debug the app? i think the name is different than the name i have. Do you have Slack or other chat application?

**Comment by steffjenl** [comment]
@Sjalabert theflyingdutchman is my username on Slack!

@j0bro great news from Athom

> Today we introduce Homey Cameras, a new feature part of Homey v2.2.0. This free software update starts rolling out to all Homey users today.
> Camera devices can now be viewed from within the Homey app — even when you’re not at home. Users can now also create a Flow to send a live snapshot to their smartphone.

**Comment by j0bro** [comment]
Yeah exactly, as a developer I already got that info somewhat earlier but life is also massively busy for me. Will have a look at it tonight I hope

**Comment by steffjenl** [comment]
@j0bro problem found, its an network problem and i will help @Sjalabert tonight with his network changes. 

@j0bro do you want help with the changes? if you can give me more information.

**Comment by j0bro** [comment]
Sure thing. And I will publish a new beta version soon to get the support for new models out in beta. I just checked the new Nest App that also supports cameras and snapshots now; we can use that as inspiration: https://github.com/athombv/com.nest/tree/nest-cam-support

**Comment by steffjenl** [comment]
@j0bro i created camera support for the Blink app today! i will create camera support for unifi maybe sunday!

i hope i get the new CloudKey soon so i can create support for this one also.

**Comment by steffjenl** [comment]
@j0bro first test / debug version created on https://github.com/steffjenl/com.ubnt.unifivideo

With camera support, last event snapshot ( i think the new snapshot will override this snapshot) and new snapshot.

**Comment by j0bro** [comment]
@sejfr6 do you still have this issue? Please retest with the recently updated v0.9.3.

**Comment by Krisstenswe** [comment]
I have tried to get this app working since Nov last year without success. The problem was that the app couldn't find my NVR and I couldn't type in and save the IP of my NVR.
I'm now running on 0.9.3 and, at last, I can type in and save the IP of the NVR and - VOILÁ - it works like a charm! :-)
Thnx!

**Comment by steffjenl** [comment]
The problem from @Sjalabert is that he is using an separated VLAN for his Homey then for the camera's. Show his Homey can't connect to his UniFi Video server,
