### ISSUE TITLE
Afterupdate to 1.1.2 App will not start

### ISSUE THREAD

**Issue by CoenRoos** [j0bro/com.ubnt.unifivideo#27]
After the update the app won't start anymore.

**Comment by j0bro** [comment]
Hey @CoenRoos could you please try this one out and let me know if it still crashes: https://homey.app/nl-nl/app/com.ubnt.unifivideo/UniFi-Video/test/

**Comment by CoenRoos** [comment]
Jeroen,

When I try to install it I get an ''Network Error', It also gives me this error even trying to install other apps, I have to resolve that one first, Will keep you posted!
________________________________

**Comment by j0bro** [comment]
I get other reports that this version did fix the issue; it is currently in review for publication.
