### ISSUE TITLE
Not seeing any NVR

### ISSUE THREAD

**Issue by rickardp** [j0bro/com.ubnt.unifivideo#9]
I tried to add the NVR/cameras but all I see is “no device found”. I am running the NVR in Docker and I am not sure I set all the ports (for example port 10001 is already used by Unifi controller (WiFi/USG, not NVR).

Maybe it would be easier to just be able to type in the URL of the NVR instead of (or as a complement to) relying on automatic discovery?

**Comment by j0bro** [comment]
Setting the NVR's IP will be a feature of the next release, I already got feedback that scanning for the NVR is not always possible due the network topology.

**Comment by 3riic** [comment]
I have the same issue.
Do you know when the next release will be available?
My NVR is on a different subnet and installed on a Windows server.

**Comment by Charlie-Root** [comment]
I have 5 cam's attached to a NVR:
2x UVC G3
2x UVC G3 Pro
1x UVC G3 Micro
1x NVR

I typed in the API key and NVR ip address but when adding devices i only see the 2x UVC G3..

**Comment by Krisstenswe** [comment]
Hi!

I’m trying to use the app UniFi Video, but it seems that Homey can’t find the NVR.
Under Homey Settings, Apps UniFi Video Settings, the field for NVR is empty.
If someone is up and running with this app - is your NVR-field empty?

My NVR is a standard NVR-box (4GB) and on the same subnet as Homey.
Homey 1.5.12. UniFi Video app 0.9.2.

**Comment by hockeymask** [comment]
Got same issue, nvr field is empty and i cant find my g3-dome.
Running 0.9.2 beta

**Comment by j0bro** [comment]
@Charlie-Root Since you won the Pro and Micro devices, can provide the device names of these devices? I would like to add support for those in the app.

@hockeymask I own the Dome myself and it should already work, however it is found as a normal UVC-G3 (it is essentially the same camera in a different housing)

**Comment by Charlie-Root** [comment]
@j0bro i did not win them, sadly. :) 
Where can i find these device names that you seek?

**Comment by j0bro** [comment]
LOL I meant OWN of course!
Could you run this tool and post back the output under the "device type" column: https://chrome.google.com/webstore/detail/ubiquiti-device-discovery/hmpigflbjeapnknladcfphgkemopofig/related

**Comment by rickardp** [comment]
This seems to work fine now. I repeated adding devices now after upgrading to Homey 2.0 and the app now discovered the NVR (same Docker setup as before). Don't know if anything changed, but I am closing this as it works for me. Please reopen if there is still an issue.
